language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
env:
  global:
    - FILE_TO_VALIDATE=beacon.yaml
    - GH_URL=https://raw.githubusercontent.com
    - VALIDATOR_URL=http://validator.swagger.io/validator/debug?url
    - URL_TO_VALIDATE=$GH_URL/$TRAVIS_REPO_SLUG/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}/$FILE_TO_VALIDATE
script:
  # validate
  - echo "Validating $URL_TO_VALIDATE:"
  - VALIDATION_OUTPUT=`curl -sS "$VALIDATOR_URL=$URL_TO_VALIDATE"`

  # print validation errors
  - echo $VALIDATION_OUTPUT

  # check if the validation output is an empty array, i.e. no errors
  - VALIDATION_ERROR_COUNT=`echo "$VALIDATION_OUTPUT" |jq -c '.schemaValidationMessages // [] | map(select(.level != "warning"))' |jq length`
